resource "aws_lambda_function" "api_lambda" {
  filename      = "../build/main.zip" # The zip generated by your Makefile
  function_name = "inventory-api-${var.environment}"
  role          = aws_iam_role.lambda_exec.arn
  handler       = "bootstrap" # Standard handler for Go in AL2023
  runtime       = "provided.al2023"
  timeout       = 30
  memory_size   = 1024
  architectures = ["arm64"]

  source_code_hash = filebase64sha256("../build/main.zip")

  environment {
    variables = {
      DATABASE_URL         = var.db_url
      ENVIRONMENT          = var.environment
      JWT_SECRET           = var.jwt_secret
      COMPANY_NAME         = var.company_name
      S3_BUCKET_NAME       = aws_s3_bucket.invoice_storage.id
      FRONTEND_URL         = "https://${var.domain_name}"
      LAMBDA_FUNCTION_NAME = "inventory-api-${var.environment}"
    }
  }
}
